include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
    - test_packages/**

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
